<a href="https://colab.research.google.com/github/kwb425/class2024Spring/blob/main/class2024Spring_0531-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

A = np.matrix('0.9 -0.4; 0.4 0.9')
b = np.matrix('1;1')
x = A*b
x

[[0.5]
 [1.3]]


matrix([[ 0.92783505,  0.41237113],
        [-0.41237113,  0.92783505]])

In [3]:
A = np.matrix('1.25 0.25; 0.25 1')
b = np.matrix('1;1')
x = A*b
x

matrix([[1.5 ],
        [1.25]])

In [4]:
A = np.matrix('1 0.5; 0.25 0.125')
b = np.matrix('1;1')
x = A*b
x

matrix([[1.5  ],
        [0.375]])

In [5]:
A = np.matrix('0.9 -0.4; 0.4 0.9')
A_inv = np.linalg.inv(A)
b = np.matrix('0.5;1.3')
x = A_inv*b
x

matrix([[1.],
        [1.]])

In [7]:
A = np.matrix('1.25 0.25; 0.25 1')
A_inv = np.linalg.inv(A)
b = np.matrix('1.5;1.25')
x = A_inv*b
x

matrix([[1.],
        [1.]])

In [8]:
A = np.matrix('1 0.5; 0.25 0.125')
A_inv = np.linalg.inv(A)
b = np.matrix('1.5;0.375')
x = A_inv*b
x

LinAlgError: Singular matrix

In [9]:
A = np.matrix('1.25 0.25; 0.25 1')
np.linalg.eig(A)

EigResult(eigenvalues=array([1.4045085, 0.8454915]), eigenvectors=matrix([[ 0.85065081, -0.52573111],
        [ 0.52573111,  0.85065081]]))